# Generated by Django 6.0.6 on 2026-07-17 16:18

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user_type', models.CharField(choices=[('client', 'Клиент'), ('employee', 'Мастер'), ('admin', 'Администратор')], default='client', verbose_name='Тип пользователя')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='Email')),
                ('is_blocked', models.BooleanField(default=False, help_text='Заблокированый пользователь не может создавать запиcи', verbose_name='Заблокирован')),
                ('first_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='Фамилия')),
                ('groups', models.ManyToManyField(blank=True, related_name='clients_users', to='auth.group', verbose_name='Группы')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='clients_permissions', to='auth.permission', verbose_name='Права доступа клиента')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
                'ordering': ('id', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user_type', models.CharField(choices=[('client', 'Клиент'), ('employee', 'Мастер'), ('admin', 'Администратор')], default='client', verbose_name='Тип пользователя')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='Email')),
                ('is_blocked', models.BooleanField(default=False, help_text='Заблокированый пользователь не может создавать запиcи', verbose_name='Заблокирован')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('work_time_hours', models.PositiveSmallIntegerField(default=8, verbose_name='Часы работы в день')),
                ('worktime_timezone', models.SmallIntegerField(default=0, verbose_name='Часовой пояс')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг мастера')),
                ('specialization', models.CharField(blank=True, max_length=255, null=True, verbose_name='Специализация')),
                ('experience_years', models.PositiveSmallIntegerField(default=0, verbose_name='Опыт работы')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='masters/photos/', verbose_name='Фото мастера')),
                ('is_available', models.BooleanField(default=False, help_text='Может ли мастер принимать записи', verbose_name='Доступен для записи')),
                ('is_verified', models.BooleanField(default=False, help_text='Подтвержден ли мастер администратором', verbose_name='Подтвержден')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Количество отзывов')),
                ('groups', models.ManyToManyField(blank=True, related_name='employees_users', to='auth.group', verbose_name='Группы')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='employees_permissions', to='auth.permission', verbose_name='Права доступа мастера')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='UsersAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user_type', models.CharField(choices=[('client', 'Клиент'), ('employee', 'Мастер'), ('admin', 'Администратор')], default='client', verbose_name='Тип пользователя')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='Email')),
                ('is_blocked', models.BooleanField(default=False, help_text='Заблокированый пользователь не может создавать запиcи', verbose_name='Заблокирован')),
                ('first_name', models.CharField(max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('groups', models.ManyToManyField(blank=True, related_name='admins_users', to='auth.group', verbose_name='Группы')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='admins_permissions', to='auth.permission', verbose_name='Права доступа админа')),
            ],
            options={
                'verbose_name': 'Администратор',
                'verbose_name_plural': 'Админитраторы',
                'db_table': 'admin_users',
            },
        ),
    ]
