# Generated by Django 6.0.6 on 2026-08-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_users_first_name_alter_users_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активный профиль'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активный профиль'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активный профиль'),
        ),
    ]
