# Generated by Django 6.0.6 on 2026-08-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_adminprofile_is_active_clientprofile_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный профиль'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный профиль'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный профиль'),
        ),
    ]
