# Generated by Django 6.0.6 on 2026-07-24 20:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PromoCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Промокод')),
                ('discount_type', models.CharField(choices=[('percent', 'Процент'), ('fixed', 'Фиксированная сумма')], default='percent', verbose_name='Тип скидки')),
                ('discount_value', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Скидка')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активен')),
                ('valid_from', models.DateTimeField(verbose_name='Начало акции')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Окончание акции')),
                ('max_usages', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Колличесво использований')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Количество использований')),
                ('only_for_new_clients', models.BooleanField(default=False, verbose_name='Только для новых клиентов')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'db_table': 'promos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Стоимость')),
                ('duration', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10)], verbose_name='Длительность услуги в минутах')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступна')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_services', to='account.employeeprofile', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Услуга мастера',
                'verbose_name_plural': 'Услуги мастеров',
                'db_table': 'employee_services',
                'ordering': ['service', 'employee'],
            },
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('status', models.CharField(choices=[('confirmed', 'Подтверждена'), ('completed', 'Выполнена'), ('cancelled', 'Отменена'), ('no_show', 'Не явился'), ('rescheduled', 'Перенесена')], default='confirmed', verbose_name='Статус')),
                ('start_at', models.DateTimeField(verbose_name='Начало записи')),
                ('end_at', models.DateTimeField(verbose_name='Окончание записи')),
                ('total_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Общая стоимость')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Сумма скидки')),
                ('final_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Итоговая стоимость')),
                ('client_notes', models.TextField(blank=True, verbose_name='Пожелания клиента')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Причина отмены')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Отправлено напоминание')),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки напоминания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='account.clientprofile', verbose_name='Клиент')),
                ('rescheduled_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='booking_manager.bookings', verbose_name='Перенесено из записи')),
                ('employee_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking_manager.employeeservice', verbose_name='Услуга мастера')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('notification_type', models.CharField(choices=[('booking_created', 'Создание записи'), ('booking_cancelled', 'Запись отменена'), ('booking_reminder', 'Напоминание о записи'), ('review_created', 'Новый отзыв'), ('system', 'Системное')], verbose_name='Тип уведомления')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('in_app', 'В приложении')], default='sms', verbose_name='Канал отправки')),
                ('status', models.CharField(choices=[('created', 'Создано'), ('sent', 'Отправлено'), ('failed', 'Ошибка')], default='created', verbose_name='Статус')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Текст')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='booking_manager.bookings')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromoUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promo_usages', to='booking_manager.bookings', verbose_name='Запись')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promo_usages', to='account.clientprofile', verbose_name='Клиент')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promo_usages', to='booking_manager.promocodes', verbose_name='Промокод')),
            ],
            options={
                'verbose_name': 'История использования промокодов',
                'verbose_name_plural': 'Истории использования промокодов',
                'db_table': 'promo_usage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('inactive', 'Неактивна'), ('archived', 'Архивирована')], default='inactive', verbose_name='Статус')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Изображение услуги')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='booking_manager.categories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'db_table': 'services',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Оценка должна быть не менее 1'), django.core.validators.MaxValueValidator(5, message='Оценка должна быть не более 5')], verbose_name='Оценка (1-5)')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст отзыва')),
                ('is_moderated', models.BooleanField(default=False, verbose_name='Отзыв прошел модерацию')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата модерации')),
                ('moderation_comment', models.TextField(blank=True, verbose_name='Комментарий модератора')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален (для скрытия без удаления из БД)')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='booking_manager.bookings', verbose_name='Запись')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='account.clientprofile', verbose_name='Клиент')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='account.employeeprofile', verbose_name='Мастер')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='booking_manager.services', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'reviews',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='employeeservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_services', to='booking_manager.services', verbose_name='Услуга'),
        ),
        migrations.CreateModel(
            name='EmployeeDayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('start_date', models.DateField(verbose_name='Начало')),
                ('end_date', models.DateField(verbose_name='Окончание')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_off', to='account.employeeprofile', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Не рабочий день',
                'verbose_name_plural': 'Не рабочие дни',
                'db_table': 'day_off',
                'ordering': ['employee', 'start_date'],
                'indexes': [models.Index(fields=['employee', 'start_date', 'end_date'], name='day_off_employe_c96022_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('weekday', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Начало')),
                ('end_time', models.TimeField(verbose_name='Конец')),
                ('is_working', models.BooleanField(default=True, verbose_name='На работе')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='account.employeeprofile', verbose_name='Расписание мастера')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
                'db_table': 'schedule',
                'ordering': ['employee', 'weekday'],
                'indexes': [models.Index(fields=['employee', 'weekday'], name='schedule_employe_874675_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'weekday'), name='unique_employee_weekday')],
            },
        ),
        migrations.AddIndex(
            model_name='bookings',
            index=models.Index(fields=['client', 'start_at'], name='bookings_client__586802_idx'),
        ),
        migrations.AddIndex(
            model_name='bookings',
            index=models.Index(fields=['employee_service', 'start_at'], name='bookings_employe_d7bab3_idx'),
        ),
        migrations.AddIndex(
            model_name='bookings',
            index=models.Index(fields=['status', 'start_at'], name='bookings_status_aac779_idx'),
        ),
        migrations.AddConstraint(
            model_name='promousage',
            constraint=models.UniqueConstraint(fields=('promo', 'client'), name='unique_client_promo_usage'),
        ),
        migrations.AddIndex(
            model_name='services',
            index=models.Index(fields=['status'], name='services_status_6676e7_idx'),
        ),
        migrations.AddIndex(
            model_name='services',
            index=models.Index(fields=['category'], name='services_categor_a61a21_idx'),
        ),
        migrations.AddConstraint(
            model_name='reviews',
            constraint=models.UniqueConstraint(fields=('client', 'booking'), name='unique_client_booking_review'),
        ),
        migrations.AddIndex(
            model_name='employeeservice',
            index=models.Index(fields=['employee'], name='employee_se_employe_3b9506_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeservice',
            index=models.Index(fields=['service'], name='employee_se_service_2d13a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeservice',
            constraint=models.UniqueConstraint(fields=('employee', 'service'), name='unique_employee_service'),
        ),
    ]
