# Generated by Django 6.0.6 on 2026-07-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='end_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание записи'),
        ),
    ]
