# Generated by Django 6.0.6 on 2026-07-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_manager', '0002_alter_bookings_end_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeschedule',
            name='weekday',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели'),
        ),
        migrations.CreateModel(
            name='SalonSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Начало работы')),
                ('end_time', models.TimeField(verbose_name='Конец работы')),
                ('is_working', models.BooleanField(default=True, verbose_name='Открыт')),
            ],
            options={
                'verbose_name': 'График работы салона',
                'verbose_name_plural': 'График работы салона',
                'db_table': 'salon_schedule',
                'ordering': ('weekday',),
                'constraints': [models.UniqueConstraint(fields=('weekday',), name='unique_salon_weekday')],
            },
        ),
    ]
