# Generated by Django 6.0.6 on 2026-07-26 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_manager', '0003_alter_employeeschedule_weekday_salonschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='booking_manager.promocodes', verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/images', verbose_name='Изображение услуги'),
        ),
    ]
