# Generated by Django 6.0.6 on 2026-08-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_manager', '0004_bookings_promo_code_alter_services_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_created', 'Создание записи'), ('booking_cancelled', 'Запись отменена'), ('booking_rescheduled', 'Запись перенесена'), ('booking_reminder', 'Напоминание о записи'), ('review_created', 'Новый отзыв'), ('system', 'Системное')], verbose_name='Тип уведомления'),
        ),
    ]
