# Generated by Django 6.0.6 on 2026-08-01 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_adminprofile_is_active_clientprofile_is_active_and_more'),
        ('booking_manager', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='client',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='account.clientprofile', verbose_name='Клиент'),
        ),
    ]
